import { Layout, Typography } from 'antd';
import type { AppProps } from 'next/app'
import Head from 'next/head';
import 'style.css';
import dotenv from 'dotenv';

const { Header } = Layout;
const { Title } = Typography;

export default function App({ Component, pageProps }: AppProps) {
  dotenv.config();

  return (
    <div>
      <Head>
        <title>Write Now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={{display: 'flex'}}>
        <Header style={{display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
          <Title style={{color: '#FFF', margin: '0px'}}>Write Now</Title>
        </Header>
      </Layout> 
      <Component {...pageProps} />
    </div>
  )
}
