import AdmissionLetterLayout from '@/admission-letter/layout/AdmissionLetterLayout';
import type { AppProps } from 'next/app'
import Head from 'next/head';
import 'style.css';

export default function App({ Component, pageProps, router }: AppProps) {
  const isInAdmissionLetter = router.pathname.startsWith('/admission-letter');

  if (isInAdmissionLetter) {
    return (
      <div>
        <Head>
          <title>Write Now</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AdmissionLetterLayout>
          <Component {...pageProps} />
        </AdmissionLetterLayout>
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Write Now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </div>
  )
}
