import Head from 'next/head'
import { ChangeEvent, useState } from 'react';

import { useGenerateChat } from '@/hooks/useGenerateChat';

export default function Home() {

  const [value, setValue] = useState<string>('');
  const [result, setResult] = useState<string | undefined>('');
  const { error, isLoading, mutate } = useGenerateChat(value);

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    setValue(event.target.value);
  }

  const handleClickButton = async() => {
    const res = await mutate('generateChat');

    setResult(res);
  }

  if (error) {
    return <>에러가 발생하였습니다.</>
  }

  if (isLoading) {
    return <>로딩중...</>
  }

  return (
    <>
      <Head>
        <title>Write Now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input onChange={handleChange} />
        <button type="submit" onClick={handleClickButton}>입력</button>
        <textarea defaultValue={result} />
      </main>
    </>
  )
}
